import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1767037749978 implements MigrationInterface {
    name = 'AutoGenerated1767037749978'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`phone\` varchar(20) NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`role\` enum ('admin', 'user', 'guest') NOT NULL DEFAULT 'user', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`settings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`organization_id\` int NOT NULL DEFAULT '1', \`group\` varchar(255) NOT NULL, \`key\` varchar(100) NOT NULL, \`value\` varchar(255) NOT NULL, \`value_type\` enum ('string', 'boolean', 'json') NOT NULL DEFAULT 'string', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`UQ_settings_unique_constraint\` (\`organization_id\`, \`key\`, \`group\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`refresh_tokens\` (\`id\` int NOT NULL AUTO_INCREMENT, \`token\` varchar(500) NOT NULL, \`userId\` int NOT NULL, \`expiresAt\` datetime NOT NULL, \`revoked\` tinyint NOT NULL DEFAULT 0, \`userAgent\` varchar(255) NULL, \`ipAddress\` varchar(45) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`agent_tasks\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`prompt\` text NOT NULL, \`logs\` longtext NULL, \`steps\` longtext NULL, \`provider\` varchar(100) NULL, \`model\` varchar(100) NULL, \`success\` tinyint NOT NULL DEFAULT 0, \`message\` text NULL, \`total_steps\` int NOT NULL DEFAULT '0', \`total_duration_seconds\` float NOT NULL DEFAULT '0', \`urls_visited\` text NULL, \`model_actions\` text NULL, \`errors\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ai_rules\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NULL, \`name\` varchar(255) NOT NULL, \`rule\` text NOT NULL, \`intent\` text NOT NULL, \`website\` varchar(255) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`refresh_tokens\` ADD CONSTRAINT \`FK_610102b60fea1455310ccd299de\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`agent_tasks\` ADD CONSTRAINT \`FK_b806c6467840547281e606ab92d\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ai_rules\` ADD CONSTRAINT \`FK_f9a38d6fac1b2fadbbaa9f94358\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`ai_rules\` DROP FOREIGN KEY \`FK_f9a38d6fac1b2fadbbaa9f94358\``);
        await queryRunner.query(`ALTER TABLE \`agent_tasks\` DROP FOREIGN KEY \`FK_b806c6467840547281e606ab92d\``);
        await queryRunner.query(`ALTER TABLE \`refresh_tokens\` DROP FOREIGN KEY \`FK_610102b60fea1455310ccd299de\``);
        await queryRunner.query(`DROP TABLE \`ai_rules\``);
        await queryRunner.query(`DROP TABLE \`agent_tasks\``);
        await queryRunner.query(`DROP TABLE \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`UQ_settings_unique_constraint\` ON \`settings\``);
        await queryRunner.query(`DROP TABLE \`settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
    }

}
